FROM confluentinc/cp-kafka:7.3.0


ENV KAFKA_BROKER_ID=1
ENV KAFKA_ZOOKEEPER_CONNECT=localhost:2181

ENV KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
ENV KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://localhost:29092
ENV KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
ENV KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
ENV KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1

# Use "exec" form so that it ]runs as PID 1 (useful for graceful shutdown)
CMD ["/usr/bin/kafka-topics", "--bootstrap-server", "localhost:9092", "--create", "--partitions", "1", "--replication-factor", "1", "--topic", "darwin"]