CREATE TABLE testdata (
  message_time TIME,
  route_id VARCHAR(255),
  unique_id VARCHAR(255),
  service_start_date DATE,
  update_origin VARCHAR(255),
  train_platform VARCHAR(255),
  working_time_pass TIME,
  working_time_arrival TIME,
  working_time_departure TIME,
  planned_time_arrival TIME,
  planned_time_departure TIME,
  actual_arrival_time TIME,
  actual_departure_time TIME,
  platform VARCHAR(255),
  train_length INT,
  estimated_time TIME,
  source VARCHAR(255),
  actual_time TIME,
  actual_time_class VARCHAR(255),
  is_delayed_arrival BOOLEAN,
  is_delayed_departure BOOLEAN,
  late_code INT,
  source_instance VARCHAR(255),
  estimated_time_minutes INT
);
